server:
  port: 9999
book:
  name: asasassa
management:
  security:
    enabled: false
spring:
  application:
    name: demo1
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:llll/eureka/